version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build Solid.js App
          command: npm run build
      - save_cache:
          key: app-build-cache-{{ .Branch }}
          paths:
            - ./dist
      - run:
          name: Deploy to Netlify
          command: ./node_modules/.bin/netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --prod --dir=dist
      - run:
          name: Check SHA
          command: echo $CIRCLE_SHA!
      - run:
          name: Register Deploy with Sleuth
          command: >
            curl -X POST "https://app.sleuth.io/api/1/deployments/bergenhemcorp/github-custom/register_deploy" \
              -H "Content-Type: application/json" \
              -d '{
              "sha": "$CIRCLE_SHA1",
              "environment": "production",
              "api_key": "4e07854a53ece429b46707ccd749992f16786360"
                }'
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main